### ISSUE TITLE
ABG_extension not showing in the webUI

### ISSUE THREAD

**Issue by EpicOddOtaku** [KutsuyaYuki/ABG_extension#1]
As the title suggests, I can find the ABG_extension anywhere in the webui
![firefox_RAuVmOoMls](https://user-images.githubusercontent.com/105439583/211764049-291084fc-3935-4078-8066-3f851f10ad8d.png)
![firefox_uwRSi2ImLb](https://user-images.githubusercontent.com/105439583/211764065-76905f3f-82dc-4b42-99f2-3edffb7089d8.png)

idk how it's fixed now

**Comment by KutsuyaYuki** [comment]
Did you restart the webui after installing the plugin? This is sometimes necessary if the requirements aren't installed yet.

**Comment by EpicOddOtaku** [comment]
Thank you for the extension
