### ISSUE TITLE
Please, write description how to use it

### ISSUE THREAD

**Issue by vredin** [KutsuyaYuki/ABG_extension#10]
Please, write description how to use it
1. I installed it using extensions
2. I see it in the combobox with scripts in the img2img
3. I upload any image, choose ABG_remover from combobox with script, push generate and get something far away from original

**Comment by Kuri-su** [comment]
how install it? run install.py? 

i try install it in sd webui extension webpage, but it not working...

**Comment by KutsuyaYuki** [comment]
Added instructions.
