### ISSUE TITLE
Background removal and then add color

### ISSUE THREAD

**Issue by Orbitalz-eth** [KutsuyaYuki/ABG_extension#13]
Not really an issue, more of a feature request.

Would it be possible for this extension to remove the background and then add a random pastel color background? 
 or even different types of color hues. vibrant, pastel, greyish, etc.

**Comment by XiaomiDE** [comment]
Custom background color would be awesome.
I tried looking for a way to do it myself but my programming goes as far as looking it up online and failing anyway... :(

Either way, great tool, thanks for making it! ♥

**Comment by KutsuyaYuki** [comment]
Added it in the latest version 😸
