### ISSUE TITLE
[feature request] - keep original resolution + remove the edges of the mask a bit

### ISSUE THREAD

**Issue by spechok** [KutsuyaYuki/ABG_extension#7]
extension works great, sadly i wasn't able to figure out how it applies the mask without screwing the algorithm completely

i want to use this feature to crop images to be viable for embedding trainings - works great, but using img2img changes the original resolution + keeps a slight "halo" around the character - would be great it we could had a slider for 1 to ~ 50 pixels to remove around the character near the transparent pixels area

**Comment by GendoG** [comment]
Agreed, it would be great to have finer control over this

**Comment by KutsuyaYuki** [comment]
This is part of the model I am using for the plugin and cannot 'fix' this, sorry.
